/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import plugin.Data;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MacBookPro
 */
public class CreateStaffConfirm extends javax.swing.JDialog {

    /**
     * Creates new form BooksPayment
     */
    public CreateStaffConfirm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbTelephone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbPosition = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        dobLabel = new javax.swing.JLabel();
        lbDOB = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbSalary = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lbProfilePhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verify");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbName.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbName.setForeground(new java.awt.Color(51, 51, 51));
        lbName.setText("Staff Name");
        lbName.setName(""); // NOI18N

        lbGender.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbGender.setForeground(new java.awt.Color(51, 51, 51));
        lbGender.setText("Gender");
        lbGender.setName(""); // NOI18N

        lbTelephone.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbTelephone.setForeground(new java.awt.Color(51, 51, 51));
        lbTelephone.setText("Telephone");
        lbTelephone.setName(""); // NOI18N

        lbEmail.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("Email");
        lbEmail.setName(""); // NOI18N

        lbPosition.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbPosition.setForeground(new java.awt.Color(51, 51, 51));
        lbPosition.setText("Position");
        lbPosition.setName(""); // NOI18N

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Staff Name");
        nameLabel.setName(""); // NOI18N

        genderLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(51, 51, 51));
        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderLabel.setText("Gender");
        genderLabel.setName(""); // NOI18N

        telephoneLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        telephoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        telephoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telephoneLabel.setText("Telephone");
        telephoneLabel.setName(""); // NOI18N

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email");
        emailLabel.setName(""); // NOI18N

        positionLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(51, 51, 51));
        positionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionLabel.setText("Position");
        positionLabel.setName(""); // NOI18N

        btnConfirm.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(51, 51, 51));
        btnConfirm.setText("Confirm");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.setFocusable(false);
        btnConfirm.setPreferredSize(new java.awt.Dimension(150, 50));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(51, 51, 51));
        dobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dobLabel.setText("Date of Birth");
        dobLabel.setName(""); // NOI18N

        lbDOB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbDOB.setForeground(new java.awt.Color(51, 51, 51));
        lbDOB.setText("Date of Birth");
        lbDOB.setName(""); // NOI18N

        lbAddress.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbAddress.setForeground(new java.awt.Color(51, 51, 51));
        lbAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddress.setText("Address");
        lbAddress.setName(""); // NOI18N

        lbSalary.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbSalary.setForeground(new java.awt.Color(51, 51, 51));
        lbSalary.setText("Salary");
        lbSalary.setName(""); // NOI18N

        salaryLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(51, 51, 51));
        salaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaryLabel.setText("Salary");
        salaryLabel.setName(""); // NOI18N

        lbStatus.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(51, 51, 51));
        lbStatus.setText("Status");
        lbStatus.setName(""); // NOI18N

        statusLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(51, 51, 51));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Status");
        statusLabel.setName(""); // NOI18N

        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(51, 51, 51));
        txtAddress.setLineWrap(true);
        txtAddress.setRows(1);
        txtAddress.setTabSize(4);
        txtAddress.setText("Address");
        txtAddress.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtAddress);

        lbProfilePhoto.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbProfilePhoto.setForeground(new java.awt.Color(51, 51, 51));
        lbProfilePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProfilePhoto.setText("Profile Photo [207 X 311]");
        lbProfilePhoto.setPreferredSize(new java.awt.Dimension(311, 207));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbProfilePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(telephoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telephoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean customerNameDetector = false;
    private boolean customerTelDetector = false;
    private boolean descriptionDetector = false;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/Form Logo.png")));
        try {Image image = ImageIO.read(getClass().getResource(CreateStaff.profilePhotoPath));lbProfilePhoto.setIcon(new ImageIcon(image));lbProfilePhoto.setText("");}catch (Exception e){}
        nameLabel.setText(CreateStaff.name);
        genderLabel.setText(CreateStaff.gender);
        telephoneLabel.setText(CreateStaff.telephone);
        emailLabel.setText(CreateStaff.email);
        dobLabel.setText(CreateStaff.dateofbirth);
        positionLabel.setText(CreateStaff.position);
        statusLabel.setText(CreateStaff.status);
        salaryLabel.setText(CreateStaff.salary);
        txtAddress.setText(CreateStaff.address);
    }//GEN-LAST:event_formWindowOpened

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyTyped

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            String name = nameLabel.getText().trim();
            String gender = genderLabel.getText().trim();
            String telephone = telephoneLabel.getText().trim();
            String email = emailLabel.getText().trim();
            String dob = dobLabel.getText().trim();
            String status = "Active";
            String salary = salaryLabel.getText().trim();
            String address = txtAddress.getText().trim();
            String position = positionLabel.getText().trim();
            String profilePhotoPath = CreateStaff.profilePhotoPath;
            
            if (position.equals("Cinema Manager"))
                position = "1";
            else if (position.equals("Concession Staff"))
                position = "2";
            else if (position.equals("Ticketing Staff"))
                position = "3";
            else if (position.equals("Usher"))
                position = "4";
            else if (position.equals("Janitor"))
                position = "5";
            else if (position.equals("Assistance Admin"))
                position = "6";
            else if (position.equals("Marketing"))
                position = "7";
            else if (position.equals("Projectionist"))
                position = "8";
            else position = "9";
            if (dob.equals("Date of Birth"))
                dob = "1996-04-18";
            Statement statement = Data.getDataConnection().createStatement();
            
            statement.execute("INSERT INTO dbmajorcineplex.tblstaff (StaffName,Gender,Birthdate,Address,Telephone,Email,Salary,Status,ProfilePhoto,PositionID) VALUES "
                                                                                            + "('"+name+"', '"+gender+"', '"+dob+"', '"+address+"', '"+telephone+"', '"+email+"', "+salary+", '"+status+"', '"+profilePhotoPath+"', "+position+");");
            
            statement.close();
            CreateStaff.created = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateStaffConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateStaffConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateStaffConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateStaffConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreateStaffConfirm().setVisible(true);
                CreateStaffConfirm dialog = new CreateStaffConfirm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPosition;
    private javax.swing.JLabel lbProfilePhoto;
    private javax.swing.JLabel lbSalary;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextArea txtAddress;
    // End of variables declaration//GEN-END:variables
}
