/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author MacBookPro
 */
public class TicketPayment extends javax.swing.JDialog {

    /**
     * Creates new form BooksPayment
     */
    public TicketPayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbMovieTitle = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbTheatre = new javax.swing.JLabel();
        lbSeat = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JLabel();
        movieTitleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        theatreLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        btnSeat = new javax.swing.JButton();
        booksCodeLabel = new javax.swing.JLabel();
        lbBooksCode = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerTel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movie Poster [207 X 300]");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 207));

        lbMovieTitle.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbMovieTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbMovieTitle.setText("Movie Title");
        lbMovieTitle.setName(""); // NOI18N

        lbDate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbDate.setForeground(new java.awt.Color(51, 51, 51));
        lbDate.setText("Date");
        lbDate.setName(""); // NOI18N

        lbTime.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbTime.setForeground(new java.awt.Color(51, 51, 51));
        lbTime.setText("Time");
        lbTime.setName(""); // NOI18N

        lbTheatre.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbTheatre.setForeground(new java.awt.Color(51, 51, 51));
        lbTheatre.setText("Theatre");
        lbTheatre.setName(""); // NOI18N

        lbSeat.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbSeat.setForeground(new java.awt.Color(51, 51, 51));
        lbSeat.setText("Seat");
        lbSeat.setName(""); // NOI18N

        lbPrice.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(51, 51, 51));
        lbPrice.setText("Price");
        lbPrice.setName(""); // NOI18N

        lbDiscount.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(51, 51, 51));
        lbDiscount.setText("Discount");
        lbDiscount.setName(""); // NOI18N

        lbSubtotal.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lbSubtotal.setText("Subtotal");
        lbSubtotal.setName(""); // NOI18N

        movieTitleLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        movieTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        movieTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTitleLabel.setText("Movie Title");
        movieTitleLabel.setName(""); // NOI18N

        dateLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("Date");
        dateLabel.setName(""); // NOI18N

        timeLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time");
        timeLabel.setName(""); // NOI18N

        theatreLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        theatreLabel.setForeground(new java.awt.Color(51, 51, 51));
        theatreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theatreLabel.setText("Theatre");
        theatreLabel.setName(""); // NOI18N

        priceLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(51, 51, 51));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price");
        priceLabel.setName(""); // NOI18N

        discountLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(51, 51, 51));
        discountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discountLabel.setText("Discount");
        discountLabel.setName(""); // NOI18N

        subtotalLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        subtotalLabel.setForeground(new java.awt.Color(51, 51, 51));
        subtotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtotalLabel.setText("Subtotal");
        subtotalLabel.setName(""); // NOI18N

        btnSeat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnSeat.setForeground(new java.awt.Color(51, 51, 51));
        btnSeat.setText("Seat");
        btnSeat.setContentAreaFilled(false);
        btnSeat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeat.setFocusable(false);
        btnSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSeatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeatMouseExited(evt);
            }
        });

        booksCodeLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        booksCodeLabel.setForeground(new java.awt.Color(51, 51, 51));
        booksCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booksCodeLabel.setText("Books Code");
        booksCodeLabel.setName(""); // NOI18N

        lbBooksCode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbBooksCode.setForeground(new java.awt.Color(51, 51, 51));
        lbBooksCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBooksCode.setText("Books Code");
        lbBooksCode.setName(""); // NOI18N

        btnConfirm.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(51, 51, 51));
        btnConfirm.setText("Confirm");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.setFocusable(false);
        btnConfirm.setPreferredSize(new java.awt.Dimension(150, 50));

        txtCustomerName.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(153, 153, 153));
        txtCustomerName.setText("Customer Name");
        txtCustomerName.setCaretColor(new java.awt.Color(51, 51, 51));
        txtCustomerName.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtCustomerName.setPreferredSize(new java.awt.Dimension(200, 45));
        txtCustomerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerNameFocusLost(evt);
            }
        });
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyTyped(evt);
            }
        });

        txtCustomerTel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtCustomerTel.setForeground(new java.awt.Color(153, 153, 153));
        txtCustomerTel.setText("Telephone Number");
        txtCustomerTel.setCaretColor(new java.awt.Color(51, 51, 51));
        txtCustomerTel.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtCustomerTel.setPreferredSize(new java.awt.Dimension(200, 45));
        txtCustomerTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerTelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerTelFocusLost(evt);
            }
        });
        txtCustomerTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerTelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerTelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbBooksCode, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booksCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTheatre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subtotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(discountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(movieTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(theatreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movieTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(theatreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTheatre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbSeat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booksCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBooksCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCustomerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean customerNameDetector = false;
    private boolean customerTelDetector = false;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/Form Logo.png")));
        if (!Books.selectedSeat.isEmpty()){
            movieTitleLabel.setText(Books.movieTitle);
            dateLabel.setText(Books.date);
            timeLabel.setText(Books.time);
            theatreLabel.setText(Books.theatre);
            btnSeat.setText(""+Books.selectedSeat);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtCustomerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerNameFocusGained
        if (!customerNameDetector){
            txtCustomerName.setCaretPosition(0);
        }
    }//GEN-LAST:event_txtCustomerNameFocusGained

    private void txtCustomerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerNameFocusLost
        String text = txtCustomerName.getText().trim();
        if (text.isEmpty()){
            txtCustomerName.setForeground(new Color(153,153,153));
            txtCustomerName.setText("Customer Name");
            customerNameDetector = false;
        }
    }//GEN-LAST:event_txtCustomerNameFocusLost

    private void txtCustomerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCustomerName.grabFocus();
        }
    }//GEN-LAST:event_txtCustomerNameKeyPressed

    private void txtCustomerNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyTyped
        txtCustomerName.setForeground(Color.DARK_GRAY);
        if (customerNameDetector == false){
            txtCustomerName.setText("");
            customerNameDetector = true;
        }
    }//GEN-LAST:event_txtCustomerNameKeyTyped

    private void txtCustomerTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerTelFocusGained
        if (!customerTelDetector){
            txtCustomerTel.setCaretPosition(0);
        }
    }//GEN-LAST:event_txtCustomerTelFocusGained

    private void txtCustomerTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerTelFocusLost
        String text = txtCustomerTel.getText().trim();
        if (text.isEmpty()){
            txtCustomerTel.setForeground(new Color(153,153,153));
            txtCustomerTel.setText("Telephone Number");
            customerTelDetector = false;
        }
    }//GEN-LAST:event_txtCustomerTelFocusLost

    private void txtCustomerTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerTelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCustomerTel.grabFocus();
        }
    }//GEN-LAST:event_txtCustomerTelKeyPressed

    private void txtCustomerTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerTelKeyTyped
        txtCustomerTel.setForeground(Color.DARK_GRAY);
        if (customerTelDetector == false){
            txtCustomerTel.setText("");
            customerTelDetector = true;
        }
    }//GEN-LAST:event_txtCustomerTelKeyTyped

    private void btnSeatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeatMouseEntered
        btnSeat.setForeground(new Color (204,153,0));
    }//GEN-LAST:event_btnSeatMouseEntered

    private void btnSeatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeatMouseExited
        btnSeat.setForeground(new Color (51,51,51));
    }//GEN-LAST:event_btnSeatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreateStaffConfirm().setVisible(true);
                TicketPayment dialog = new TicketPayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booksCodeLabel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSeat;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBooksCode;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbMovieTitle;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSeat;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTheatre;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel movieTitleLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel theatreLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTel;
    // End of variables declaration//GEN-END:variables
}
